# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

schedules:
- cron: "0 */2 * * *"
  displayName: Hourly build
  branches:
    include:
    - main
  always: true

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  pool: sonic-ubuntu-1c
  jobs:
  - job: Build
    timeoutInMinutes: 240
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install azure.core azure.kusto.data azure.kusto.ingest azure.storage.blob azure.storage.queue
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10

        # Install Azure cli
        # Wait for apt lock to be released
        while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for apt lock to be released..."
          sleep 5
        done
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      displayName: Install build tools

    - script: |
        python3 azure-pipelines/scripts/publish-mssonic-logs.py
      env:
        # Must configure pipeline variable "MANAGED_IDENTITY_ID", set it to client ID of "sonic-automation-umi"
        MANAGED_IDENTITY_ID: $(MANAGED_IDENTITY_ID)
      displayName: Ingest data into kusto
